apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    tier: backend  # Updated to reflect the required label
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: v1  # Correct selector to match the Pod labels
  template:
    metadata:
      labels:
        app: v1  # Labels should match the selector
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.0  # Specified version of the nginx image
        ports:
        - containerPort: 80
